# Generated by Django 5.2.8 on 2025-11-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(verbose_name='النص أو الرابط')),
                ('fill_color', models.CharField(default='#000000', max_length=7, verbose_name='لون المربعات')),
                ('back_color', models.CharField(default='#ffffff', max_length=7, verbose_name='لون الخلفية')),
                ('box_size', models.PositiveIntegerField(default=10, verbose_name='حجم المربعات')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='الشعار (اختياري)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='عدد الزيارات')),
                ('downloads_count', models.PositiveIntegerField(default=0, verbose_name='عدد التحميلات')),
            ],
            options={
                'verbose_name': 'رمز QR',
                'verbose_name_plural': 'رموز QR',
                'ordering': ['-created_at'],
            },
        ),
    ]
